name: Build
on:
  push:
    branches:
      - main

jobs:
  export:
    name: Export JavaScript Assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # TODO: nvmrc
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      # - uses: expo/expo-github-action@v5
      #   with:
      #     expo-version: 3.x
      #     expo-packager: npm
      #     expo-cache: true
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: npx expo export --public-url https://gregbrimble.com/
      - uses: actions/upload-artifact@v2
        with:
          name: JavaScript Assets
          path: dist/
