name: Build
on:
  push:
    branches:
      - main

jobs:
  export:
    name: Export JavaScript Assets
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # TODO: nvmrc
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-packager: npm
          expo-cache: true
      - run: npm ci
      - run: expo export --public-url https://gregbrimble.com/
      # TODO: Save as GitHub Actions Artifacts
